#!/bin/bash
# Set the paths to the two files
FILE1="/path/to/file1"
FILE2="/path/to/file2"

# Check if the files are different
if ! cmp -s "$FILE1" "$FILE2"
then
    # Sync the changes from file1 to file2
    cp "$FILE1" "$FILE2"
fi
